export const RESET_ERROR_MESSAGE = "RESET_ERROR_MESSAGE";

export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const REQUEST_LOGIN_SUCCESS = "REQUEST_LOGIN_SUCCESS";
export const REQUEST_LOGIN_FAILURE = "REQUEST_LOGIN_FAILURE";

export const REQUEST_LOGOUT = "REQUEST_LOGOUT";
export const REQUEST_LOGOUT_SUCCESS = "REQUEST_LOGOUT_SUCCESS";

export const REQUEST_ACCOUNTBYID = "REQUEST_ACCOUNTBYID";
export const REQUEST_ACCOUNTS = "REQUEST_ACCOUNTS";
export const RECEIVE_ACCOUNTS = "RECEIVE_ACCOUNTS";
export const REQUEST_ACCOUNTS_FAILURE = "REQUEST_ACCOUNTS_FAILURE";

export const REQUEST_TRANSACTIONS = "REQUEST_TRANSACTIONS";
export const RECEIVE_TRANSACTIONS = "RECEIVE_TRANSACTIONS";
export const REQUEST_TRANSACTIONS_FAILURE = "REQUEST_TRANSACTIONS_FAILURE";
export const SHOW_NEW_ACCOUNTS_FORM = "SHOW_NEW_ACCOUNTS_FORM";
export const HIDE_NEW_ACCOUNTS_FORM = "HIDE_NEW_ACCOUNTS_FORM";

export const CREATE_ACCOUNT_REQUEST = "CREATE_ACCOUNT_REQUEST";
export const CREATE_ACCOUNT_VALIDATION_FAILURE =
  "CREATE_ACCOUNT_VALIDATION_FAILURE";
export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
export const CREATE_ACCOUNT_FAILED = "CREATE_ACCOUNT_FAILED";

export const SHOW_TRANSFER_FUNDS = "SHOW_TRANSFER_FUNDS";
export const HIDE_TRANSFER_FUNDS = "HIDE_TRANSFER_FUNDS";

export const TRANSFER_FUNDS_VALIDATION_FAILURE =
  "TRANSFER_FUNDS_VALIDATION_FAILURE";

export const CREATE_TRANSACTION_REQUEST = "CREATE_TRANSACTION_REQUEST";
export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS";
export const CREATE_TRANSACTION_FAILED = "CREATE_TRANSACTION_FAILED";

export const UPDATE_ACCOUNT_BALANCE_REQUEST = "UPDATE_ACCOUNT_BALANCE_REQUEST";
export const UPDATE_ACCOUNT_BALANCE_SUCCESS = "UPDATE_ACCOUNT_BALANCE_SUCCESS";
export const UPDATE_ACCOUNT_BALANCE_FAILED = "UPDATE_ACCOUNT_BALANCE_FAILED";
